version: "3.8"

services:
    app:
        container_name: docker-react-c
        image: docker-react-i
        build: 
            context: .
        ports:
            - 4200:80
            
#Final version-2023-06-30